-- local home = os.getenv("HOME")
-- local config = {
--     cmd = {
--         "/opt/homebrew/Cellar/jdtls/1.32.0/bin/jdtls",
--         "-javaagent:/Users/davidschluter/.local/share/java/lombok.jar",
--     },
--     root_dir = vim.fs.dirname(vim.fs.find({"gradlew", ".git", "mvnw"}, {upward = true})[1])
-- }
-- require("jdtls").start_or_attach(config)
